export enum ConversationIntent {
  SMALL_TALK = 'SMALL_TALK',
  VIEW_MENU = 'VIEW_MENU',
  VIEW_ORDER = 'VIEW_ORDER',
  ASK_QUESTION = 'ASK_QUESTION',
  ORDER_FOOD = 'ORDER_FOOD',
  TRACK_ORDER = 'TRACK_ORDER',
  PAYMENT_REQUEST = 'PAYMENT_REQUEST',
  SUPPORT = 'SUPPORT',
  BUSINESS_HOURS = 'BUSINESS_HOURS',
  BUSINESS_LOCATION = 'BUSINESS_LOCATION',
  DELIVERY_INFO = 'DELIVERY_INFO',
  PAYMENT_METHODS = 'PAYMENT_METHODS',
  PRODUCT_QUERY = 'PRODUCT_QUERY',
  PRODUCT_ATTRIBUTE_QUESTION = 'PRODUCT_ATTRIBUTE_QUESTION',
  GENERAL_QUESTION = 'GENERAL_QUESTION',
  UNKNOWN = 'UNKNOWN'
}
