export enum ConversationIntent {
  SMALL_TALK = 'SMALL_TALK',
  VIEW_MENU = 'VIEW_MENU',
  VIEW_ORDER = 'VIEW_ORDER',
  ASK_QUESTION = 'ASK_QUESTION',
  ORDER_FOOD = 'ORDER_FOOD',
  TRACK_ORDER = 'TRACK_ORDER',
  PAYMENT_REQUEST = 'PAYMENT_REQUEST',
  SUPPORT = 'SUPPORT',
  UNKNOWN = 'UNKNOWN'
}
